src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Repository\TournamentRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TournamentRepository::class)]
class Tournament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $tournament_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?string $rewards = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $team_count = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $player_team_count = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255)]
    private ?string $poster = null;

   
    #[ORM\ManyToMany(targetEntity: Club::class, mappedBy: 'tournaments')]
    private Collection $clubs;



    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, Game>
     */
    #[ORM\OneToMany(targetEntity: Game::class, mappedBy: 'tournament', orphanRemoval: true)]
    private Collection $games;

    #[ORM\ManyToOne(inversedBy: 'tournaments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $creator = null;

    public function __construct()
    {
        
        $this->clubs = new ArrayCollection();
        $this->created_at = new DateTimeImmutable();
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTournamentName(): ?string
    {
        return $this->tournament_name;
    }

    public function setTournamentName(string $tournament_name): static
    {
        $this->tournament_name = $tournament_name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getRewards(): ?string
    {
        return $this->rewards;
    }

    public function setRewards(string $rewards): static
    {
        $this->rewards = $rewards;

        return $this;
    }

    public function getTeamCount(): ?int
    {
        return $this->team_count;
    }

    public function setTeamCount(int $team_count): static
    {
        $this->team_count = $team_count;

        return $this;
    }

    public function getPlayerTeamCount(): ?int
    {
        return $this->player_team_count;
    }

    public function setPlayerTeamCount(int $player_team_count): static
    {
        $this->player_team_count = $player_team_count;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

   

    /**
     * @return Collection<int, Club>
     */
    public function getClubs(): Collection
    {
        return $this->clubs;
    }

    public function addClub(Club $club): static
    {
        if (!$this->clubs->contains($club)) {
            $this->clubs->add($club);
            $club->addTournament($this);
        }

        return $this;
    }

    public function removeClub(Club $club): static
    {
        if ($this->clubs->removeElement($club)) {
            $club->removeTournament($this);
        }

        return $this;
    }

  

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }
}

src/Controller/Back/TournamentRegistrationController.php
<?php
namespace App\Controller\Back;

use App\Entity\Tournament;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;

class TournamentRegistrationController extends AbstractController
{
    // Route pour le processus d'inscription à un tournoi
    #[Route('/tournament/{id}/register', name: 'app_tournament_register_process', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function processRegistration(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        // Récupération de l'utilisateur courant
        $user = $this->getUser();

        // Vérification si l'utilisateur est connecté
        if (!$user) {
            $this->addFlash('error', 'Vous devez être connecté pour vous inscrire à un tournoi.');
            return $this->redirectToRoute('app_login');
        }

        // Récupération du club de l'utilisateur
        $club = $user->getClub();

        // Vérification si le club est déjà inscrit au tournoi
        $isAlreadyRegistered = $club->getTournaments()->contains($tournament);

        if (!$isAlreadyRegistered) {
            // Si non inscrit, ajouter le tournoi au club
            $club->addTournament($tournament);
            $entityManager->persist($club);
            $entityManager->flush();
        } else {
            // Si déjà inscrit, afficher un message d'information
            $this->addFlash('info', 'Vous êtes déjà inscrit à ce tournoi.');
        }

        // Redirection vers la page d'accueil du compte
        return $this->redirectToRoute('app_account_home');
    }
}

src/Controller/TournamentRegistrationController.php
<?php
namespace App\Controller;

use App\Entity\Tournament;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;

class TournamentRegistrationController extends AbstractController
{
   

    #[Route('/tournament/{id}/register', name: 'app_tournament_register_process', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function processRegistration(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if (!$user) {
            $this->addFlash('error', 'Vous devez être connecté pour vous inscrire à un tournoi.');
            return $this->redirectToRoute('app_login');
        }
        $club = $user->getClub();
        $isAlreadyRegistered = $club->getTournaments()->contains($tournament);

        if (!$isAlreadyRegistered) {
            $club->addTournament($tournament);
            $entityManager->persist($club);
            $entityManager->flush();
        } else {
            $this->addFlash('info', 'Vous êtes déjà inscrit à ce tournoi.');
        }

        return $this->redirectToRoute('app_account_home');
    }
}

templates/tournament_registration/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page du Tournoi{% endblock %}

{% block body %}

<!-- Main Content -->
<div class="container mt-4">
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('info') %}
        <div class="alert alert-info">
            {{ message }}
        </div>
    {% endfor %}
    <div class="row">
        <div class="col text-center">
            <div class="rounded-pill bg-dark d-inline-block p-3">
                <h2 class="section-title m-0">{{ tournament.tournamentName }}</h2>
            </div>
            <p class="section-description"></p>
        </div>
    </div>
</div>

<div class="container mt-4 semi-transparent-bg-white text-center text-black mb-4">
    <div class="row align-items-center">
        <div class="col-md-4 mb-4 mb-md-0">
            <img src="{{ asset('images/' ~ tournament.poster) }}" class="img-fluid rounded-start" alt="Image du tournoi">
        </div>
        <div class="col-md-8">
            <h2 class="section-title text-black">{{ tournament.tournamentName }}</h2>
            <div class="table-responsive">
                <table class="table table-bordered mt-4">
                    <tbody>
                        <tr>
                            <th scope="row" style="width: 30%;"><i class="bi bi-geo-alt-fill icon-tournoi"></i> Lieu :</th>
                            <td style="width: 70%;">{{ tournament.location }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-calendar-date icon-tournoi"></i> Date :</th>
                            <td>{{ tournament.date|date('d F Y') }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-people-fill icon-tournoi"></i> Nombre d'équipes :</th>
                            <td>{{ tournament.teamCount }} équipes</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-trophy-fill icon-tournoi"></i> Nombre de joueur/équipe :</th>
                            <td>{{ tournament.playerTeamCount }} joueurs</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-cash-coin icon-tournoi"></i> Prix par équipe :</th>
                            <td>{{ tournament.price }} €</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-trophy-fill icon-tournoi"></i> Récompenses :</th>
                            <td>{{ tournament.rewards }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center mt-4">
                {% if app.user %}
                    {% if isAlreadyRegistered %}
                        <p class="alert alert-info">Vous êtes déjà inscrit à ce tournoi.</p>
                        {# todo ajouter un bouton pour revenir à la liste des tournois et changer de tournoi #}
                        <div class="text-center mt-4 mb-2">
                <a href="{{ path('app_tournament_browse') }}" class="btn btn-success">Retour à la liste des tournois</a>
                        </div>
                    {% else %}
                        <form method="post" action="{{ path('app_tournament_register_process', {'id': tournament.id}) }}">
                            <button type="submit" class="fs-4 px-4 py-3 rounded pen-icon-solo text-decoration-none text-black btn btn-secondary">
                                J'inscris mon équipe
                            </button>
                        </form>
                    {% endif %}
                {% else %}
                    <a href="{{ path('app_login') }}" class="fs-4 px-4 py-3 rounded pen-icon-solo text-decoration-none text-black btn btn-secondary">
                        <i class="bi bi-person me-2"></i> Connectez-vous pour vous inscrire
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}