src/Entity/Club.php
<?php

// App/Entity/Club.php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClubRepository::class)]
class Club
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $club_name = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $licence_number = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\ManyToMany(targetEntity: Tournament::class, inversedBy: 'clubs')]
    private Collection $tournaments;

    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'club')]
    private Collection $users;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    public function __construct()
    {
        $this->tournaments = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable(); // Initialisation de la date de création
    }

    // ... autres getters et setters

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClubName(): ?string
    {
        return $this->club_name;
    }

    public function setClubName(string $club_name): static
    {
        $this->club_name = $club_name;

        return $this;
    }

    public function getLicenceNumber(): ?int
    {
        return $this->licence_number;
    }

    public function setLicenceNumber(int $licence_number): static
    {
        $this->licence_number = $licence_number;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, Tournament>
     */
    public function getTournaments(): Collection
    {
        return $this->tournaments;
    }

    public function addTournament(Tournament $tournament): static
    {
        if (!$this->tournaments->contains($tournament)) {
            $this->tournaments->add($tournament);
        }

        return $this;
    }

    public function removeTournament(Tournament $tournament): static
    {
        $this->tournaments->removeElement($tournament);

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setClub($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getClub() === $this) {
                $user->setClub(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/Back/ClubBackController.php
<?php

namespace App\Controller\Back;

use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/club/back')]
class ClubBackController extends AbstractController
{
    #[Route('/', name: 'app_club_back_index', methods: ['GET'])]
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('club_back/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_club_back_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $club = new Club();
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($club);
            $entityManager->flush();

            return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('club_back/new.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_back_show', methods: ['GET'])]
    public function show(Club $club): Response
    {
        return $this->render('club_back/show.html.twig', [
            'club' => $club,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_club_back_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('club_back/edit.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_back_delete', methods: ['POST'])]
    public function delete(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$club->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($club);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/ClubBackController.php
<?php

namespace App\Controller;

use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/club/back')]
class ClubBackController extends AbstractController
{
    #[Route('/', name: 'app_club_back_index', methods: ['GET'])]
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('club_back/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_club_back_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $club = new Club();
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($club);
            $entityManager->flush();

            return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('club_back/new.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_back_show', methods: ['GET'])]
    public function show(Club $club): Response
    {
        return $this->render('club_back/show.html.twig', [
            'club' => $club,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_club_back_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('club_back/edit.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_back_delete', methods: ['POST'])]
    public function delete(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$club->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($club);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_club_back_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/club_back/_delete_form.html.twig
<form method="post" action="{{ path('app_club_back_delete', {'id': club.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
    <button class="btn btn-danger mt-1 mb-2">Supprimer</button>
</form>

templates/club_back/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/club_back/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Club{% endblock %}

{% block body %}
<div class="container mt-4 custom-contact-container">
    <div class="row">
        <div class="col text-center">
            <div class="rounded-pill bg-dark d-inline-block p-3">
                <h2 class="section-title m-0">Edition d'un club</h2>
            </div>
        </div>
    </div>
<div class="container mt-2">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12 semi-transparent-bg-white p-4 text-center text-black">
                {{ include('club_back/_form.html.twig') }}
<div class="text-center mt-2 ">
                    
                </div>

                {{ include('club_back/_delete_form.html.twig') }}
                <a href="{{ path('app_club_back_index') }}" class="btn btn-secondary mb-2 mt-2">Retour à la liste des clubs</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/club_back/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club index{% endblock %}

{% block body %}
{% if is_granted('ROLE_ADMIN') %}
<div class="container mt-4 custom-contact-container">
    <div class="row">
        <div class="col text-center">
            <div class="rounded-pill bg-dark d-inline-block p-3">
                <h2 class="section-title m-0">Liste des clubs</h2>
            </div>
        </div>
    </div>

<div class="container table-container mt-4 mb-4">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-md-10 col-sm-12 semi-transparent-bg-white p-4 text-center text-black">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th class="align-middle">Id</th>
                                <th class="align-middle">Nom du Club</th>
                                <th class="align-middle">Numéro de licence</th>
                                <th class="align-middle">Adresse du club</th>
                                <th class="align-middle">Logo</th>
                                <th class="align-middle">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
        <tbody>
        {% for club in clubs %}
            <tr>
                <td>{{ club.id }}</td>
                <td>{{ club.clubName }}</td>
                <td>{{ club.licenceNumber }}</td>
                <td>{{ club.adress }}</td>
                <td>{{ club.logo }}</td>
                <td>
                    <a href="{{ path('app_club_back_show', {'id': club.id}) }}" class="btn btn-success btn-sm mb-2">Voir</a>
                    <a href="{{ path('app_club_back_edit', {'id': club.id}) }}" class="btn btn-warning btn-sm mb-2">Editer</a>
                <form action="{{ path('app_club_back_delete', {'id': club.id}) }}" method="post" class="d-inline">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
                                        {# <button type="submit" class="btn btn-danger btn-sm mb-2">Supprimer</button> #}
                                    </form>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="12" class="text-center">Aucun enregistrement trouvé</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    <div class="text-center mt-4 mb-3">
                        <a href="{{ path('app_club_back_new') }}" class="btn btn-secondary">Créer un nouveau club</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger text-center">
                    <h2>Accès Refusé</h2>
                    <p>Vous n'avez pas les permissions nécessaires pour accéder à cette page.</p>
                    <a href="{{ path('app_main') }}" class="btn btn-secondary mt-3">Retour à l'accueil</a>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/club_back/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Club{% endblock %}

{% block body %}
    <div class="container mt-4 custom-contact-container">
    <div class="row">
        <div class="col text-center">
            <div class="rounded-pill bg-dark d-inline-block p-3">
                <h2 class="section-title m-0">Ajouter un club</h2>
            </div>
        </div>
    </div>
    </div>
    <div class="container mt-4 mb-4">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12 semi-transparent-bg-white p-4 text-center text-black">
    {{ include('club_back/_form.html.twig') }}
    <div class="text-center mt-2 mb-2">
        <a href="{{ path('app_club_back_index') }}" class="btn btn-secondary">Retour à la liste des clubs</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/club_back/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
<div class="container mt-4 custom-contact-container">
    <div class="row">
        <div class="col text-center">
            <div class="rounded-pill bg-dark d-inline-block p-3">
                <h2 class="section-title m-0">{{ club.clubName }}</h2>
            </div>
        </div>
    </div>

    <div class="container mt-4 mb-4">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12 semi-transparent-bg-white p-4 text-center">
                <table class="table table-bordered table-hover">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ club.id }}</td>
                        </tr>
                        <tr>
                            <th>Nom du Club</th>
                            <td>{{ club.clubName }}</td>
                        </tr>
                        <tr>
                            <th>Numéro de Licence</th>
                            <td>{{ club.licenceNumber }}</td>
                        </tr>
                        <tr>
                            <th>Adresse</th>
                            <td>{{ club.adress }}</td>
                        </tr>
                        <tr>
                            <th>Logo</th>
                            <td>{{ club.logo }}</td>
                        </tr>
                        <tr>
                            <th>Créé le</th>
                            <td>{{ club.createdAt ? club.createdAt|date('Y-m-d') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Mis à jour le</th>
                            <td>{{ club.updatedAt ? club.updatedAt|date('Y-m-d') : '' }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="text-center mt-4">
                    <a href="{{ path('app_club_back_index') }}" class="btn btn-secondary">Retour à la liste</a>
                    <a href="{{ path('app_club_back_edit', {'id': club.id}) }}" class="btn btn-warning ml-2">Éditer</a>
                    {{ include('club_back/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}